### ISSUE TITLE
Revision Reminder

### ISSUE THREAD

**Issue by ndylanl** [ndylanl/MacroADATeam04Afternoon#45]
- [x] 1. fix label to make it more see-able. 
- [x] 2. can repeat every monday, tuesday, wednesday, etc.

COA: different color and more attention brought to label, can set reminder to specific days.

**Comment by geraldchester** [comment]
for the "every certain day" repeat options, kalau bisa opsi nya ga cuma 1 hari tapi bisa beberapa hari. misal:

repeat every sunday di tick,
repeat every monday juga bisa di tick.
