### ISSUE TITLE
Update Reminder #2

### ISSUE THREAD

**Issue by gogumaru** [ndylanl/MacroADATeam04Afternoon#58]
- [x] user can choose multiple repeats
- [x] hover color if pressed (in reminder list view)
- [x] change default category if edit reminder
- [x] save apakah user menyelesaikan reminder
- [x] change reminder list view empty state
- [x] add repeats option in reminder list view

**Comment by geraldchester** [comment]
first one is hardest. kelar hari ini ((should be)).
